### ISSUE TITLE
Program is a pervert

### ISSUE THREAD

**Issue by Neelgodly** [AdityaJS12321/Password-Generator#4]
![image](https://user-images.githubusercontent.com/98798122/152488739-a926a1ed-00c3-416b-a388-bc071d909932.png)

**Comment by AdityaJS12321** [comment]
Literally who cares bruh just cope with your very efficiently made  password

**Comment by Neelgodly** [comment]
> Literally who cares bruh just cope with your very efficiently made and unique password

Crap. what was the whole point of entering  a hint, 5 minutes of my life wasted! Sux. Shame on the stupid dumb-ass cringe af developers who came up with such a uniquely and efficiently shitty program. Please don't make any more programs in future, you'll get better paid then

**Comment by AdityaJS12321** [comment]
See, ill explain

Jazz is fluent and relaxing just like the wind, and wind gives out the vibes to sleep together 
ez af

**Comment by Neelgodly** [comment]
> See, ill explain
> 
> Jazz is fluent and relaxing just like the wind, and wind gives out the vibes to sleep together ez af to rember

Yep, totally makes sense, thanks for the help

**Comment by AdityaJS12321** [comment]
Well, ig we can close this issue now. Thanks for the cooperation :)
